<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\C64Lib\C64Lib.csproj" />
  </ItemGroup>

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Optimize>true</Optimize>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
