<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="SpriteData.asm" />
    <None Remove="TestDecoration.aas" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SpriteData.asm" />
    <EmbeddedResource Include="TestDecoration.aas" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\C64Lib\C64Lib.csproj" />
  </ItemGroup>

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Optimize>true</Optimize>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
